name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.head_commit.id }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install modules
        run: yarn

      - name: Build with Yarn
        run: yarn build

      - name: Store distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: book-reviews
          path: ${{ github.workspace }}/build

      - name: scp pipeline
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.JEANTESSIER_HOST }}
          user: ${{ secrets.JEANTESSIER_USER }}
          pass: ${{ secrets.JEANTESSIER_PASS }}
          scp: |
            ./build/* => "/home/jeantessier/jeantessier.com/BookReviews/"
            ./build/index.html => "/home/jeantessier/jeantessier.com/Books.html"
            ./build/index.html => "/home/jeantessier/jeantessier.com/BooksBackLog.html"
            ./build/index.html => "/home/jeantessier/jeantessier.com/SoftwareEngineering/Books.html"
            ./build/index.html => "/home/jeantessier/jeantessier.com/SoftwareEngineering/BooksBackLog.html"
