name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.head_commit.id }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install modules
        run: yarn

      - name: Build with Yarn
        run: yarn build

      - name: Store distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: book-reviews
          path: ${{ github.workspace }}/build
